### ISSUE TITLE
Have no idea what I'm doing wrong

### ISSUE THREAD

**Issue by PossiblyIsaac** [d4rkc0d3r/d4rkAvatarOptimizer#12]
I only have the VRchatSDK and the add-on in the project adding a model still give me this error.
Assets\d4rkAvatarOptimizer\src\d4rkAvatarOptimizerEditor.cs(2840,54): error CS0117: 'AvatarValidation' does not contain a definition for 'RemoveIllegalComponents'

**Comment by d4rkc0d3r** [comment]
Do you have the Avatars 3.0 SDK in your project? It only works with that one. 2.0 or the worlds SDK is incompatible with this tool.

**Comment by PossiblyIsaac** [comment]
I'm using SDK 3.0 the latest I just installed unity today (Unity 2019.4.31f1)

**Comment by PossiblyIsaac** [comment]
Older versions of the SDK work with it (2022.05.04.17.47) the newest version of the SDK does not (2022.10.12.21.07)

**Comment by d4rkc0d3r** [comment]
Thanks, I'll look into the new SDK.
